name: Build and Scan with SonarQube

on:
  push:
    branches:
      - main

jobs:
  scan-with-sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      ## No tests defined
      # - name: Run tests
      #   run: npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Fail deployment when the Quality Gate status is red
      - uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-docker-image:
    if: ${{ needs.scan-with-sonarqube.result == 'success' }}
    needs: scan-with-sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t morufajibikehub/nodejs-hello-world:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u morufajibikehub --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push morufajibikehub/nodejs-hello-world:latest