name: Build our Node.js app

# Controls when the action will run.
on:
  # Triggers the workflow on push event but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Build the app
        run: npm run build

      # Uploads a file as a build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist